# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - dashBoardPoiVolume:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  dashBoardPoiVolume: